### ISSUE TITLE
Conflict between the logger, deepcopy and ipython

### ISSUE THREAD

**Issue by MarkusSchwarz1980** [blond-admin/BLonD#111]
I was trying to run example 18 in ipython.  There is a conflict between the logger, deepcopy and ipython resulting in a TypeError when 'matched_from_distribution_function' calls deepcopy of the RingAndRFTracker, which contains a logger instance.

There is no error when running the example with python (either through command line or eclipse). When commenting out lines 231,232 in tracker.py, which create the logging instance, the example also runs in ipython.

**Comment by kiliakis** [comment]
I've come across many issues with deepcopy, either runtime errors or memory issues, so I suggest to remove it completely or use it as little as possible.

**Comment by scpalbright** [comment]
For what it's worth I got it with this error:  "TypeError: can't pickle _thread.RLock objects" when using iPython, which is probably the same one as Markus.

I propose where it's used only the necessary parameters are copied in a more sanitary way.  I think the main user is @alasheen
