### ISSUE TITLE
synchronous data type string to bool

### ISSUE THREAD

**Issue by scpalbright** [blond-admin/BLonD#124]
Ring object defaults synchronous data type as a string ("momentum"), which is then passed to RingOptions to be used in place of the bool input_is_momentum in the reshape_data function.  This can probably be made more explicit.

It might also be worth using parenthesise in 
``if input_is_momentum and interp_time == 't_rev':''
To ensure correct treatment.

**Comment by alasheen** [comment]
The first point is corrected in https://github.com/blond-admin/BLonD/pull/121
I can include the second point soon

**Comment by alasheen** [comment]
Added parenthesis to if statements with "and" in pull request https://github.com/blond-admin/BLonD/pull/121
