### ISSUE TITLE
unittests with try except too big

### ISSUE THREAD

**Issue by scpalbright** [blond-admin/BLonD#141]
the test_beam_object unittests have the entirety of 3 tests wrapped in a try/except for TypeError due to the deepcopy issues, which I think is a bad idea.  The try block should be as small as possible or we could miss bugs caused by something else, and perhaps in this sort of case include a string comparison to check it is the error we think it is, thoughts?

**Comment by kiliakis** [comment]
@scpalbright yes indeed, the try except block should only include the call to matched_from_distribution. Can you change this together with the unit-tests for beam that you wanted to add?

**Comment by scpalbright** [comment]
sure

**Comment by scpalbright** [comment]
Modified in latest push, will be included in pull request.
