### ISSUE TITLE
C++ setup fails on synchrotron_radiation

### ISSUE THREAD

**Issue by htimko** [blond-admin/BLonD#186]
Warning: The compiled blond library was not found.
        You can safely ignore this warning if you are in 
        the process of compiling the library.
running compile
Enable Multi-threaded code:  False
Using boost:  False
With FFTW3:  False
C++ Compiler:  g++
Compiler flags:  -O3 -ffast-math -std=c++11 -shared -fPIC
Extra libraries:  
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
/Users/timko/PycharmProjects/BLonD_master/blond/synchrotron_radiation/synchrotron_radiation.cpp:81:51: error: initializer for thread-local variable must be a constant expression
            static __thread normal_distribution<> dist(0.0, 1.0);
                                                  ^~~~~~~~~~~~~~
/Users/timko/PycharmProjects/BLonD_master/blond/synchrotron_radiation/synchrotron_radiation.cpp:81:51: note: use 'thread_local' to allow this
/Users/timko/PycharmProjects/BLonD_master/blond/synchrotron_radiation/synchrotron_radiation.cpp:140:51: error: initializer for thread-local variable must be a constant expression
            static __thread normal_distribution<> dist(0.0, 1.0);
                                                  ^~~~~~~~~~~~~~
/Users/timko/PycharmProjects/BLonD_master/blond/synchrotron_radiation/synchrotron_radiation.cpp:140:51: note: use 'thread_local' to allow this
2 errors generated.

Compilation failed.

**Comment by blond-admin** [comment]
I could not replicate the error, if when using a clang compiler, so I will close the issue for now. 
If it appears again in the future, we will have another look at it.
