### ISSUE TITLE
Swap in the fwhm_multibuch returned values

### ISSUE THREAD

**Issue by alasheen** [blond-admin/BLonD#193]
Bunch length and positions are swapped in [fwhm_multibuch](https://github.com/blond-admin/BLonD/blob/13b8f10b3b82e7f7e878ce5b7b8948d5ac5caa10/blond/toolbox/filters_and_fitting.py#L194) and [rms_multibuch](https://github.com/blond-admin/BLonD/blob/13b8f10b3b82e7f7e878ce5b7b8948d5ac5caa10/blond/toolbox/filters_and_fitting.py#L221)

I will include a fix in a coming PR.

**Comment by blond-admin** [comment]
Fixed in merge request: https://gitlab.cern.ch/blond/BLonD/-/merge_requests/3
