### ISSUE TITLE
Replace "is" check statements by "=="

### ISSUE THREAD

**Issue by alasheen** [blond-admin/BLonD#195]
To prevent death by thousand warnings

**Comment by MarkusSchwarz1980** [comment]
Continuing with the line of thought, it would be a good idea to replace all numpy aliases to builtin data types (like `np.int`), since they are deprecated in numpy version 1.20; see [here](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) and throw `DeprecationWarnings`.

**Comment by kiliakis** [comment]
Both issues:
1. '==' instead of 'is' where suggested
2. Use np.int32, np.int64 or int in place of np.int
have been fixed.
