### ISSUE TITLE
LXplus pip install blond fails in virtual environment

### ISSUE THREAD

**Issue by mvadai** [blond-admin/BLonD#198]
To reproduce:

python3 -m venv blond
source blond/bin/activate
pip install blond

Fails with: 
    SystemExit:
    Beginning with Matplotlib 3.4, Python 3.7 or above is required.
    You are using Python 3.6.8.

Also fails on scipy>=1.6.

Fix is simple, need to explicitly specify matplotlib and scipy versions and install these before blond.

python3 -m venv blond
source blond/bin/activate
pip install 'matplotlib>3,<3.4'
pip install 'scipy>1.4,<1.6'
pip install blond

See: https://docs.scipy.org/doc/scipy/reference/release.1.6.0.html
And https://github.com/matplotlib/matplotlib/blob/v3.4.0rc1/setup.py vs https://github.com/matplotlib/matplotlib/blob/v3.3.4/setup.py
After installing the correct matplotlib and scipy versions, the other install methods work, too.

**Comment by kiliakis** [comment]
Thanks @mvadai , the issue is now solved in the latest version of blond (2.1.1) published in Pypi!
