### ISSUE TITLE
Compile parallel code with TDM-GCC

### ISSUE THREAD

**Issue by kiliakis** [blond-admin/BLonD#26]
The C routines in the code are using openmp to express parallelism. However, openmp is not installed by default with TDM-GCC. The users have to check the box named openmp during the installation process of TDM-GCC if they want to use the multithreaded version. 
@dquartul, @htimko We could add a note for this in BLonD's site installation instructions.

**Comment by dquartul** [comment]
I added a comment in the instructions

**Comment by kiliakis** [comment]
Thanks @dquartul !
