### ISSUE TITLE
BLonD compiled version not up to date

### ISSUE THREAD

**Issue by htimko** [blond-admin/BLonD#28]
The BLonD compiled version linked on the website are not up to date. 

In the user installation guide https://blond.web.cern.ch/content/user-installation-guide
there is a link to v 1.14.2, https://gitlab.cern.ch/dquartul/BLonD/tags

In the developer installation guide https://blond.web.cern.ch/content/developer-installation-guide
there is a link to 1.15.1, https://github.com/dquartul/BLonD/releases

Please update both links with the latest version of the code, v 1.16.0
Thank you!

**Comment by dquartul** [comment]
fixed!
