### ISSUE TITLE
object has no attribute 'assertRaisesRegex'

### ISSUE THREAD

**Issue by kiliakis** [blond-admin/BLonD#57]
Screenshot taken from [python 3 docs](https://docs.python.org/3.3/library/unittest.html):

![screenshot from 2017-06-21 15-18-01](https://user-images.githubusercontent.com/11835649/27386047-d7e3e602-5694-11e7-9188-59e0e6e29d20.png)

The method `assertRaisesRegexp()` was renamed to `assertRaisesRegex()` in python 3.2 version. As a result, 4 more tests fail in python 2.7 due to` "object has no attribute 'assertRaisesRegex' "`.

**Comment by scpalbright** [comment]
If it's only used in unit tests you could use:
```
import sys
if int(sys.version[0]) == 3:
    assertRaisesRegex
else:
    assertRaisesRegexp
```

**Comment by alasheen** [comment]
The if correction works well, can be added in the setUp function of all the unittests objects (I started with general_parameters test)

**Comment by kiliakis** [comment]
Issue not relevant anymore since we are not supporting python 2.7
