### ISSUE TITLE
Problem with python3 and synchrotron radiation

### ISSUE THREAD

**Issue by badjo42** [blond-admin/BLonD#58]
Issue using python3, anaconda4 fresh installation, GCC 6.2 (last official release from cvmfs)

OSError: libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by sync_rad.so)

This issue comes from the c++ code inside quantum_excitation_std.cpp (std::random)

With the pyhton3 installation in the blond folder, it works ... but then for a new user, installing anaconda from scratch it won't work

**Comment by kiliakis** [comment]
After some experimentation we saw that it is more of a compiler issue than a blond or anaconda issue. So it is safe to use gcc 4.8.X or 4.9.X with a new anaconda installation or the one installed on the blond user. gcc 5 and gcc 6 produce this error.

**Comment by alasheen** [comment]
Can you try "conda install libgcc" on your fresh install to see if it solves the problem ?

**Comment by badjo42** [comment]
It solves the problem =)

We should add this somewhere in the installation procedure!
