### ISSUE TITLE
Documentation and comments for combine_rf_functions()

### ISSUE THREAD

**Issue by htimko** [blond-admin/BLonD#61]
Preprocess.py has been cleaned-up
https://github.com/htimko/BLonD/blob/clean-up/input_parameters/preprocess.py

After merging with main fork, combine_rf_functions() will require a revision of the documentation and adding some comments in the code -> for Simon

**Comment by scpalbright** [comment]
Updated documentation, more detail can be added if desired.  Pull request opened for the new documentation.
