### ISSUE TITLE
bunch length for imaginary gamma transition

### ISSUE THREAD

**Issue by byeer** [blond-admin/BLonD#62]
To simulate the the machine with imaginary gamma transition the RF wave should be shifted by Pi ,  this present some problems with you simulated the beam distribution using bi-gaussian, because for short bunch length (shorter than 100 ns), the plots  show the beam energy to zero, even when you indicate in the distribution a different value.

**Comment by htimko** [comment]
The plots are done w.r.t. the synchronous energy, so energy is shown as relative energy offset. The bi-gaussian function generates a distribution with (i) an r.m.s. energy width that is matched (w/o intensity effects) to the r.m.s. bunch length, if the energy spread is not specified, and a (ii) non-matched bi-gaussian with the specified r.m.s. time and energy spreads if both quantities are specified. In both cases, the distribution is generated around the synchronous phase and energy.

If you want the distribution to have an energy offset, please add it manually after generation,
beam.dE += my_offset_value
