### ISSUE TITLE
Clean up input_check()

### ISSUE THREAD

**Issue by htimko** [blond-admin/BLonD#63]
Revise and clean up input_check() in RFParams. Do something similar in GeneralParams??

**Comment by htimko** [comment]
Can be performed now.

**Comment by alasheen** [comment]
See 30d8d39ac1ee7de5dbb82c496b6b706bc79aac75

**Comment by alasheen** [comment]
See 30d8d39ac1ee7de5dbb82c496b6b706bc79aac75
