### ISSUE TITLE
Bug in histogram_par.cpp for large number of slices

### ISSUE THREAD

**Issue by badjo42** [blond-admin/BLonD#81]
In histogram_par.cpp, in the nonsmooth function:

-- the hist array is initialized using MAX_SLICES = 100000. For simulations with a very large number of slices (2 batches of 72 bunches spaced by 5 buckets, 256 slices per bucket), it ends up with bunches at the wrong place.

Quick fix: increase this number

**Comment by kiliakis** [comment]
@badjo42 I am working on it for a proper solution ;)

**Comment by kiliakis** [comment]
check discussion #87

**Comment by kiliakis** [comment]
Not using a static allocation anymore, the bug has been fixed.
