### ISSUE TITLE
Probably outdated version of plot_slices.plot_beam_profile_derivative()

### ISSUE THREAD

**Issue by kiliakis** [blond-admin/BLonD#9]
In lines [55-63 of plot_slices.py](https://github.com/dquartul/BLonD/blob/master/plots/plot_slices.py#L55-L63) we can see that `plot_beam_profile_derivative()` is calling `Slices.beam_profile_derivative()` passing an integer type argument (1, 2, or 3). However [`beam_profile_derivative()`](https://github.com/dquartul/BLonD/blob/master/beams/slices.py#L327-L350) method is waiting for a string type argument ('diff', 'gradient', 'filter1d') thus resulting in an error. 
This seems like a previous version of `beam_profile_derivative()` method was a using an integer to specify the way to calculate the derivative, but then this changed to a string. @alasheen , @juanfem could you please confirm so that I can propose a fix?

**Comment by juanfem** [comment]
I think you are right, but I have never used that method. However, I don't see any other possible explanation.

**Comment by juanfem** [comment]
Fixed by #10
